enum SCREEN_NAME {
  INVENTORY_STACK = 'InventoryStack',
  NEW_PRODUCT_STACK = 'NewProductStack',
  HOME_SCREEN = 'HomeScreen',
}
enum SCREEN_NAME_TITLE {
  INVENTORY_STACK = 'Inventory',
  NEW_PRODUCT_STACK = 'New Product',
  HOME_SCREEN = 'Home',
}

const getScreenTitles = (title: SCREEN_NAME): string => {
  const SCREENS = {
    [SCREEN_NAME.NEW_PRODUCT_STACK]: SCREEN_NAME_TITLE.NEW_PRODUCT_STACK,
    [SCREEN_NAME.INVENTORY_STACK]: SCREEN_NAME_TITLE.INVENTORY_STACK,
    [SCREEN_NAME.HOME_SCREEN]: SCREEN_NAME_TITLE.HOME_SCREEN,
  };
  return SCREENS[title];
};

export {SCREEN_NAME, SCREEN_NAME_TITLE, getScreenTitles};
