export default {
  topbar: {
    greetings: 'Wellcome Back',
  },
  workshop: {
    uploadImage: 'Upload Workshop Logo',
    name: 'Workshop Name',
    description: 'Workshop Description',
    createWorkshop: 'Create Workshop',
  },
  input: {
    search: 'Search',
    name: 'Name',
    description: 'Description',
    price: 'Price',
    stock: 'Stock',
    album: 'Album',
    selectCategory: 'Select Category',
    productName: 'Product Name',
    productDescription: 'Product Description',
    productBrand: 'Product Brand',
    productPrice: 'Product Price',
    productStock: 'Product Stock',
    uploadImage: 'Upload Image',
    categoryName: 'Category Name',
    bannerTitle: 'Banner Title',
    showIn: 'Show In',
    relatedCategories: 'Related Categories',
    modal: {
      selectCategoryTitle: 'Select Category',
    },
    characteristic: {
      addCharacteristic: 'Add Characteristic',
      modalTitle: 'Characteristic',
      icon: 'Icono',
      title: 'Title',
      description: 'Description',
    },
  },
  home: {
    productList: 'Product List',
  },
  productDetails: {
    confirmationDeleteMessage: 'Are you sure you want to delete this product?',
  },
  addProduct: {
    productCover: 'Product Cover',
    availableProducts: 'Available Products',
    album: 'Album',
  },
  addCategory: {
    title: 'New Category',
    cover: 'Cover',
  },
  addBanner: {
    title: 'New Banner',
    bannerImages: 'Banner Images',
  },
  confirmation: {
    titleCongratulations: 'Congratulations',
    confirmationProduct: 'Your product has been successfully added',
    confirmationCategory: 'Your category has been successfully added',
  },
  settings: {
    title: 'Settings',
    Workspace: 'Store',
    Profile: 'Profile',
    Categories: 'Categories',
    Products: 'Products',
    Banner: 'Banner',
    Logout: 'Logout',
  },
  editProfile: {
    profileImage: 'Profile Image',
    username: 'Username',
    country: 'Country',
    state: 'State',
    age: 'Age',
    bio: 'Bio',
  },
  logIn: {
    title: 'Log In',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
  },
  signUp: {
    title: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    alreadyHaveAccount: 'Already have an account?',
  },
  button: {
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    add: 'Add',
    next: 'Next',
    confirm: 'Confirm',
    continue: 'Continue',
    signIn: 'Log In',
    signUp: 'Sign Up',
  },
  error: {
    error: 'Error',
    characteristicExists: 'This characteristic already exists',
    allFieldsRequired: 'All fields are required',
  },
  titleScreen: {
    INVENTORY_STACK: 'Inventory',
    NEW_PRODUCT_STACK: 'New Product',
    HOME_SCREEN: 'Home',
    PRODUCT_DETAILS_SCREEN: 'Product Details',
    ADD_PRODUCT_SCREEN: 'Add Product',
    ADD_PRODUCT_SCREEN_PT2: 'Add Product',
    CONFIRM_DETAILS_SCREEN: 'Confirm Details',
    CONFIRMATION_SCREEN: 'Confirm Screen',
    AUTH_STACK: 'Auth',
    LOGIN_SCREEN: 'Login',
    SIGNUP_SCREEN: 'Signup',
    SETTINGS_STACK: 'Settings',
    SETTINGS_SCREEN: 'Settings',
    NEW_CATEGORY_SCREEN: 'Add Category',
    ICON_HELP_SCREEN: 'Help',
    NEW_BANNER_SCREEN: 'Add Banner',
    CATEGORY_STOCK_SCREEN: 'Category Stock',
    PRODUCT_STOCK_SCREEN: 'Product Stock',
    SELECT_ITEM_SCREEN: 'Select New',
    PROFILE_SCREEN: 'Profile',
    EDIT_PROFILE_SCREEN: 'Edit Profile',
  },
};
