export default {
  topbar: {
    greetings: 'Bienvenido de nuevo',
  },
  workshop: {
    uploadImage: 'Subir Logo del Workshop',
    name: 'Nombre',
    description: 'Descripción',
    createWorkshop: 'Crear Workshop',
  },
  input: {
    search: 'Buscar',
    name: 'Nombre',
    description: 'Descripción',
    price: 'Precio',
    stock: 'Stock',
    album: 'Album',
    selectCategory: 'Seleccionar Categoría',
    productName: 'Nombre del producto',
    productDescription: 'Descripción del producto',
    productBrand: 'Marca del Producto',
    productPrice: 'Precio del Producto',
    productStock: 'Stock del Producto',
    uploadImage: 'Subir Imagen',
    categoryName: 'Nombre de la Categoría',
    relatedCategories: 'Categorías Relacionadas',
    bannerTitle: 'Título del Banner',
    showIn: 'Mostrar en',
    modal: {
      selectCategoryTitle: 'Seleccionar Categoría',
    },
    characteristic: {
      addCharacteristic: 'Agregar Característica',
      modalTitle: 'Característica',
      icon: 'Icono',
      title: 'Titulo',
      description: 'Descripción',
    },
  },
  home: {
    productList: 'Lista de Productos',
  },
  productDetails: {
    confirmationDeleteMessage: '¿Estás seguro de eliminar este producto?',
  },
  addProduct: {
    productCover: 'Imagen de Producto',
    availableProducts: 'Productos Disponibles',
    album: 'Album',
  },
  addCategory: {
    title: 'Nueva Categoría',
    cover: 'Imagen de Categoría',
  },
  addBanner: {
    title: 'Nuevo Banner',
    bannerImages: 'Imagenes de Banner',
  },
  confirmation: {
    titleCongratulations: 'Felicidades',
    confirmationProduct: 'Su producto ha sido agregado exitosamente',
    confirmationCategory: 'Su Categoría ha sido agregada exitosamente',
  },
  settings: {
    Workspace: 'Store',
    title: 'Configuración',
    Profile: 'Perfil',
    Categories: 'Categorías',
    Products: 'Productos',
    Banner: 'Banner',
    Logout: 'Cerrar sesión',
  },
  editProfile: {
    profileImage: 'Imagen de Perfil',
    username: 'Nombre de Usuario',
    country: 'Pais',
    state: 'Estado',
    age: 'Edad',
    bio: 'Bio',
  },
  logIn: {
    title: 'Iniciar sesión',
    email: 'Correo',
    password: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
  },
  signUp: {
    title: 'Registrarse',
    username: 'Nombre de Usuario',
    email: 'Correo',
    password: 'Contraseña',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
  },
  button: {
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    save: 'Guardar',
    add: 'Agregar',
    next: 'Siguiente',
    confirm: 'Confirmar',
    continue: 'Continuar',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
  },
  error: {
    error: 'Error',
    characteristicExists: 'Ya existe esta característica',
    allFieldsRequired: 'Todos los campos son obligatorios',
  },
  titleScreen: {
    INVENTORY_STACK: 'Inventario',
    NEW_PRODUCT_STACK: 'Nuevo Producto',
    HOME_SCREEN: 'Inicio',
    PRODUCT_DETAILS_SCREEN: 'Detalles de Producto',
    ADD_PRODUCT_SCREEN: 'Agregar Producto',
    ADD_PRODUCT_SCREEN_PT2: 'Agregar Producto',
    CONFIRM_DETAILS_SCREEN: 'Confirmar Detalles',
    CONFIRMATION_SCREEN: 'Confirmación',
    AUTH_STACK: 'Autenticación',
    LOGIN_SCREEN: 'Iniciar sesión',
    SIGNUP_SCREEN: 'Registrar',
    SETTINGS_STACK: 'Configuración',
    SETTINGS_SCREEN: 'Configuración',
    NEW_CATEGORY_SCREEN: 'Agregar Categoría',
    ICON_HELP_SCREEN: 'Ayuda',
    NEW_BANNER_SCREEN: 'Agregar Banner',
    CATEGORY_STOCK_SCREEN: 'Inventario de Categorías',
    PRODUCT_STOCK_SCREEN: 'Inventario de Productos',
    SELECT_ITEM_SCREEN: 'Seleccionar',
    PROFILE_SCREEN: 'Perfil',
    EDIT_PROFILE_SCREEN: 'Editar Perfil',
  },
};
